# Site settings
title: "Coding Dragon"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: gadol.park@gmail.com
description: Meaning of Life
url: "http://eweing.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username:
github_username:  eweing

# Build settings
markdown: kramdown
